@extends('layouts.app') @section('title', $siteSettings['seo_title'])
@section('content')<section class="hero"><div class="orb orb-a"></div><div class="orb orb-b"></div><div class="container hero-grid"><div class="hero-copy"><span class="kicker"><i></i> Ideias que viram presentes</span><h1>{{ $siteSettings['hero_title'] }}</h1><p>{{ $siteSettings['hero_subtitle'] }}</p><div class="hero-actions"><a class="btn primary" href="{{ $siteSettings['hero_url'] ?: route('catalog') }}">{{ $siteSettings['hero_cta'] }} <span>→</span></a><a class="btn ghost" href="{{ route('pages.show','quem-somos') }}">Conheça a Gift Lab</a></div><div class="hero-proof"><div><strong>Presentes</strong><span>para surpreender</span></div><div><strong>Criações</strong><span>cheias de personalidade</span></div></div></div><div class="hero-art"><div class="hero-card card-main"><img src="{{ ($siteSettings['hero_image'] ? Storage::url($siteSettings['hero_image']) : ($siteSettings['logo'] ? Storage::url($siteSettings['logo']) : asset('images/gift-lab-logo.png'))) }}" alt="Gift Lab"><span>Seu próximo presente incrível começa aqui.</span></div><div class="float-chip chip-one">✦ Feito para encantar</div><div class="float-chip chip-two">⌁ Geek, casa & criatividade</div><div class="lab-dots"></div></div></div></section>
@if($siteSettings['home_categories']==='1')<section class="section container"><div class="section-heading"><div><span class="kicker">Explore o laboratório</span><h2>Um universo de possibilidades</h2></div><a href="{{ route('catalog') }}">Todas as categorias →</a></div><div class="category-grid">@forelse($categories as $category)<a class="category-card" href="{{ route('categories.show',$category) }}"><span class="category-icon">@if($category->image)<img src="{{ Storage::url($category->image) }}" alt="" loading="lazy">@else{{ $category->icon ?: ['✦','⌂','◈','♟','❋','⌁'][$loop->index%6] }}@endif</span><div><strong>{{ $category->name }}</strong><small>{{ $category->products_count }} produtos</small></div><span>↗</span></a>@empty @foreach(['Impressão 3D','Action Figures','Geek','Games Retrô','Casa','Presentes'] as $name)<div class="category-card muted"><span class="category-icon">✦</span><div><strong>{{ $name }}</strong><small>Em breve</small></div></div>@endforeach @endforelse</div></section>
@endif @if($siteSettings['home_featured']==='1')<section class="section soft"><div class="container"><div class="section-heading"><div><span class="kicker">Seleção especial</span><h2>{{ $siteSettings['title_featured'] }}</h2></div><a href="{{ route('catalog',['sort'=>'recent']) }}">Ver todos →</a></div><div class="products-grid">@forelse($featured as $product)<x-product-card :product="$product"/>@empty <div class="empty-state"><span>✦</span><h3>As primeiras criações estão ganhando forma.</h3><p>Volte em breve para descobrir os destaques da Gift Lab.</p></div>@endforelse</div></div></section>
@endif @if($siteSettings['home_about']==='1')<section class="container story-banner"><div><span class="kicker light">Criatividade sem rótulos</span><h2>Não é só um presente.<br>É uma história para lembrar.</h2><p>{{ $siteSettings['home_story'] }}</p><a class="btn white" href="{{ route('pages.show','quem-somos') }}">Nossa história →</a></div><div class="story-symbol">G<span>✦</span>L</div></section>
@endif @if($siteSettings['home_social']==='1')<section class="section container newsletter"><div><span class="kicker">Novidades da Gift Lab</span><h2>Algo incrível está sempre chegando.</h2><p>Acompanhe nossos canais e seja o primeiro a descobrir novas criações.</p></div><a class="btn primary" href="{{ route('contact') }}">Fale com a Gift Lab →</a></section>@endif
@if($siteSettings['home_banners']==='1')<section class="container">@foreach($banners as $banner)<article class="public-banner">@if($banner->desktop_image)<picture>@if($banner->mobile_image)<source media="(max-width:760px)" srcset="{{ Storage::url($banner->mobile_image) }}">@endif<img src="{{ Storage::url($banner->desktop_image) }}" alt="{{ $banner->title }}" loading="lazy"></picture>@endif<h2>{{ $banner->title }}</h2><p>{{ $banner->subtitle }}</p>@if($banner->url)<a class="btn primary" href="{{ $banner->url }}" rel="noopener noreferrer">{{ $banner->button_label ?: 'Saiba mais' }}</a>@endif</article>@endforeach</section>@endif
@if($siteSettings['home_new']==='1')@include('components.home-products',['items'=>$newProducts,'title'=>$siteSettings['title_new']])@endif
@if($siteSettings['home_promotions']==='1')@include('components.home-products',['items'=>$promotions,'title'=>$siteSettings['title_promotions']])@endif
@if($siteSettings['home_customizable']==='1')@include('components.home-products',['items'=>$customizableProducts,'title'=>$siteSettings['title_customizable']])@endif
@if($siteSettings['home_popular']==='1')@include('components.home-products',['items'=>$popular,'title'=>$siteSettings['title_popular']])@endif
@endsection
