@extends('layouts.app')
@php($markdownOptions = ['html_input' => 'strip', 'allow_unsafe_links' => false, 'renderer' => ['soft_break' => "<br>\n"]])
@php($descriptionHtml = Str::markdown($product->short_description ?: $product->description ?? '', $markdownOptions))
@php($plainDescription = trim(preg_replace('/\s+/', ' ', html_entity_decode(preg_replace('/<[^>]+>/', ' ', $descriptionHtml), ENT_QUOTES | ENT_HTML5, 'UTF-8'))))
@section('title', $product->name.' — Gift Lab')
@section('description', $plainDescription ?: 'Conheça este produto da Gift Lab.')
@section('og_image', $product->primaryImage ? url(Storage::url($product->primaryImage->path)) : asset('images/gift-lab-logo.png'))
@section('content')
<div class="container breadcrumbs"><a href="{{ route('home') }}">Início</a><span>›</span><a href="{{ route('catalog') }}">Produtos</a><span>›</span><span>{{ $product->name }}</span></div>
<section class="container product-detail">
<div class="gallery"><div class="main-image media-stage" data-media-stage>@if($product->images->count())<img src="{{ Storage::url($product->images->first()->path) }}" alt="{{ $product->name }}">@elseif($product->videos->count())<iframe src="{{ $product->videos->first()->embed_url }}" title="{{ $product->name }}" allowfullscreen></iframe>@else<div class="product-placeholder"><span>✦</span><small>Fotos e vídeos em breve</small></div>@endif</div>
@if($product->images->count() || $product->videos->count())<div class="thumbs media-thumbs">@foreach($product->images as $image)<button type="button" data-media-thumb data-media-type="image" data-media-src="{{ Storage::url($image->path) }}" data-media-title="{{ $image->alt ?: $product->name }}"><img src="{{ Storage::url($image->path) }}" alt="{{ $image->alt }}"></button>@endforeach @foreach($product->videos as $video)<button type="button" class="video-thumb" data-media-thumb data-media-type="video" data-media-src="{{ $video->embed_url }}" data-media-title="{{ $video->title ?: $product->name }}"><img src="{{ $video->thumbnail_url }}" alt="Vídeo"><span>▶</span></button>@endforeach</div>@endif
@foreach($product->videos as $video)<a class="youtube-link" href="{{ $video->watch_url }}" target="_blank" rel="noopener noreferrer">Abrir {{ $video->title ?: 'vídeo' }} no YouTube ↗</a>@endforeach</div>
<div class="product-copy"><div class="product-category-tags detail-category-tags">@foreach($product->categories as $category)<a href="{{ route('categories.show',$category) }}">#{{ $category->name }}</a>@endforeach</div><h1>{{ $product->name }}</h1><div class="lead markdown-content markdown-content--short">{!! Str::markdown($product->short_description ?? '', $markdownOptions) !!}</div><div class="availability {{ $product->is_available?'yes':'no' }}"><i></i>{{ $product->made_to_order?'Produzido sob encomenda':($product->is_available?'Disponível':'Indisponível') }}</div>
@if($product->customizable)<div class="customizable"><span>✎</span><div><strong>Personalize do seu jeito</strong><p>Este produto pode ser personalizado.</p></div></div>@endif
<div class="sales-box"><h2>Escolha onde comprar</h2><p>Compare os valores. <strong>Os preços abaixo não incluem frete.</strong></p>@forelse($product->salesLinks as $link)<a href="{{ $link->url }}" class="channel-button" target="_blank" rel="noopener noreferrer" style="--channel:{{ $link->channel->color?:'#7139C6' }}"><span>{{ $link->channel->name }}</span><strong>{{ $link->price ? 'R$ '.number_format($link->price,2,',','.') : 'Consultar preço' }}</strong><small>Abrir anúncio ↗</small></a>@empty<a class="channel-button contact" href="{{ route('contact') }}">Consultar formas de compra</a>@endforelse<small>A compra é concluída no canal externo escolhido.</small></div>
<form class="shipping-box" action="{{ route('products.shipping',$product) }}" data-shipping-form><h2>Calcular frete</h2><p>O frete é calculado separadamente e será somado ao valor do produto.</p><div><label><span>Seu CEP</span><input name="postal_code" inputmode="numeric" autocomplete="postal-code" placeholder="00000-000" required></label><button class="btn ghost" type="submit">Calcular</button></div><section class="shipping-results" data-shipping-result aria-live="polite"></section></form>
<div class="share" data-share-content data-share-title="{{ $product->name }}" data-share-text="{{ Str::limit($plainDescription,140) }}" data-share-image="{{ $product->primaryImage?url(Storage::url($product->primaryImage->path)):'' }}"><span>Compartilhar:</span><button data-share>Compartilhar</button><button data-copy-link>Copiar link</button><button class="favorite-button inline" data-favorite="{{ $product->id }}">♡ Favoritar</button></div></div>
</section>
<section class="container product-description"><div><span class="kicker">Sobre o produto</span><h2>Detalhes que fazem a diferença</h2><div class="prose markdown-content">{!! Str::markdown($product->description ?? '', $markdownOptions) !!}</div></div>@if($product->attributes->count())<aside><h3>Características</h3>@foreach($product->attributes as $attribute)<div><span>{{ $attribute->name }}</span><strong>{{ $attribute->value }} {{ $attribute->unit }}</strong></div>@endforeach</aside>@endif</section>
@if($product->is_bundle && $product->bundleItems->count())<section class="section soft bundle-public"><div class="container"><div class="section-heading"><div><span class="kicker">Itens inclusos</span><h2>O que vem neste conjunto</h2></div></div><div class="bundle-public-grid">@foreach($product->bundleItems as $item)<article>@if($item->primaryImage)<img src="{{ Storage::url($item->primaryImage->path) }}" alt="{{ $item->name }}">@else<div class="bundle-placeholder">✦</div>@endif<div><strong>{{ $item->name }}</strong><span>{{ $item->pivot->quantity }} {{ $item->pivot->quantity > 1 ? 'unidades' : 'unidade' }}</span></div></article>@endforeach</div></div></section>@endif
@if($related->count())<section class="section soft"><div class="container"><div class="section-heading"><h2>Você também pode gostar</h2></div><div class="products-grid">@foreach($related as $item)<x-product-card :product="$item"/>@endforeach</div></div></section>@endif
@endsection
