@extends('layouts.admin')
@section('title', 'Vendas')
@section('heading', 'Registrar vendas')
@section('content')
@include('admin.finance.nav')
<div class="finance-layout"><section class="admin-card finance-form"><span class="kicker">Nova entrada</span><h2>Registrar venda</h2><form method="post" action="{{ route('admin.finance.sales.store') }}">@csrf
<label>Produto <b class="required-mark">*</b><select name="product_id" required><option value="">Selecione</option>@foreach($products as $product)<option value="{{ $product->id }}" @selected(old('product_id') == $product->id)>{{ $product->name }}{{ $product->is_bundle ? ' (Conjunto)' : '' }}</option>@endforeach</select></label>
<div class="form-grid"><label>Quantidade <b class="required-mark">*</b><input type="number" name="quantity" min="1" value="{{ old('quantity', 1) }}" required></label><label>Valor unitário (R$) <b class="required-mark">*</b><input type="number" name="unit_price" min="0.01" step="0.01" value="{{ old('unit_price') }}" required></label><label>Frete recebido (R$)<input type="number" name="shipping_income" min="0" step="0.01" value="{{ old('shipping_income', 0) }}"></label><label>Taxas descontadas (R$)<input type="number" name="fee" min="0" step="0.01" value="{{ old('fee', 0) }}"></label></div>
<label>Canal de venda<select name="sales_channel_id"><option value="">Venda direta</option>@foreach($channels as $channel)<option value="{{ $channel->id }}" @selected(old('sales_channel_id') == $channel->id)>{{ $channel->name }}</option>@endforeach</select></label>
<label>Data da venda <b class="required-mark">*</b><input type="date" name="sold_at" value="{{ old('sold_at', now()->toDateString()) }}" required></label><label>Observações<textarea name="notes" rows="3">{{ old('notes') }}</textarea></label><button class="btn primary">Registrar venda</button></form></section>
<section class="admin-card"><h2>Vendas registradas</h2><div class="finance-records">@forelse($sales as $sale)<article><div><strong>{{ $sale->quantity }}× {{ $sale->product_name }}</strong><small>{{ $sale->sold_at->format('d/m/Y') }} · {{ $sale->channel?->name ?: 'Venda direta' }}</small></div><b class="money-in">R$ {{ number_format($sale->net_total, 2, ',', '.') }}</b><form method="post" action="{{ route('admin.finance.sales.destroy', $sale) }}" data-confirm data-confirm-title="Excluir venda?" data-confirm-message="A entrada será removida do extrato." data-confirm-label="Excluir">@csrf @method('delete')<button class="text-danger">Excluir</button></form></article>@empty<div class="finance-empty">Nenhuma venda registrada.</div>@endforelse</div>{{ $sales->links() }}</section></div>
@endsection
