<section class="admin-card">
<input type="hidden" name="details_present" value="1">
<h2>Características e variações</h2>
<label>Tags (separadas por vírgula)<input name="tags_text" value="{{ old('tags_text', $product->exists ? $product->tags->pluck('name')->implode(', ') : '') }}"></label>
<label>Observações da condição<textarea name="condition_notes">{{ old('condition_notes', $product->condition_notes) }}</textarea></label>
<div data-repeat-editor="attributes"><div class="card-head"><h3>Características</h3><button type="button" class="btn ghost" data-repeat-add>Adicionar característica</button></div><div data-repeat-list>
@foreach(old('attributes', $product->exists ? $product->attributes->toArray() : []) as $index=>$attribute)
<div class="form-grid" data-repeat-row><label>Nome<input name="attributes[{{ $index }}][name]" value="{{ $attribute['name'] }}" required></label><label>Valor<input name="attributes[{{ $index }}][value]" value="{{ $attribute['value'] }}" required></label><label>Unidade<input name="attributes[{{ $index }}][unit]" value="{{ $attribute['unit'] ?? '' }}"></label><button type="button" data-repeat-remove>Remover</button></div>
@endforeach</div><template><div class="form-grid" data-repeat-row><label>Nome<input name="attributes[__KEY__][name]" required></label><label>Valor<input name="attributes[__KEY__][value]" required></label><label>Unidade<input name="attributes[__KEY__][unit]"></label><button type="button" data-repeat-remove>Remover</button></div></template></div>
<div data-repeat-editor="variants"><div class="card-head"><h3>Variações</h3><button type="button" class="btn ghost" data-repeat-add>Adicionar variação</button></div><p>Descreva tamanho/cor no nome. O acréscimo é uma referência para o cliente; confirme o valor final no canal de venda.</p><div data-repeat-list>
@foreach(old('variants', $product->exists ? $product->variants->toArray() : []) as $index=>$variant)
<div class="form-grid" data-repeat-row><label>Nome (ex.: M / Preto)<input name="variants[{{ $index }}][name]" value="{{ $variant['name'] }}" required></label><label>SKU opcional<input name="variants[{{ $index }}][sku]" value="{{ $variant['sku'] ?? '' }}"></label><label>Estoque<input type="number" min="0" name="variants[{{ $index }}][stock]" value="{{ $variant['stock'] ?? '' }}"></label><label>Ajuste de preço (R$)<input type="number" step="0.01" name="variants[{{ $index }}][price_adjustment]" value="{{ $variant['price_adjustment'] ?? 0 }}" required></label><input type="hidden" name="variants[{{ $index }}][active]" value="0"><label class="check"><input type="checkbox" name="variants[{{ $index }}][active]" value="1" @checked($variant['active'] ?? false)> Ativa</label><button type="button" data-repeat-remove>Remover</button></div>
@endforeach</div><template><div class="form-grid" data-repeat-row><label>Nome (ex.: M / Preto)<input name="variants[__KEY__][name]" required></label><label>SKU opcional<input name="variants[__KEY__][sku]"></label><label>Estoque<input type="number" min="0" name="variants[__KEY__][stock]"></label><label>Ajuste de preço (R$)<input type="number" step="0.01" name="variants[__KEY__][price_adjustment]" value="0" required></label><input type="hidden" name="variants[__KEY__][active]" value="0"><label class="check"><input type="checkbox" name="variants[__KEY__][active]" value="1" checked> Ativa</label><button type="button" data-repeat-remove>Remover</button></div></template></div>
</section>
